services:
  - type: web
    name: sicpl-backend
    env: php
    buildCommand: composer install --optimize-autoloader --no-dev && php artisan config:cache && php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ToCKsPVoVyXFsEmTwvcZCEytrUaKMroT